Document: libwxadditions28
Title: Debian libwxadditions28 Manual
Author: <insert document author here>
Abstract: This manual describes what libwxadditions28 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libwxadditions28/libwxadditions28.sgml.gz

Format: postscript
Files: /usr/share/doc/libwxadditions28/libwxadditions28.ps.gz

Format: text
Files: /usr/share/doc/libwxadditions28/libwxadditions28.text.gz

Format: HTML
Index: /usr/share/doc/libwxadditions28/html/index.html
Files: /usr/share/doc/libwxadditions28/html/*.html

  
